### ISSUE TITLE
Be confornment with the XDG standard for user config storage location

### ISSUE THREAD

**Issue by wilzbach** [storyscript/cli#120]
[The XDG standard](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) is kinda a thing on Linux.

As this can become difficult, there is e.g. this package: https://github.com/ActiveState/appdirs, but sth. like this should work for the config directory:

```py
def get_config_dir(app):
    if sys.platform == 'win32':
        p = getenv('APPDATA')
    elif sys.platform == 'darwin':
        p = path.expanduser('~/Library/Application Support')
    else:
        p = getenv('XDG_CONFIG_HOME', path.expanduser("~/.config"))
    return path.join(p, app)
```

Might require a migration or least a fallback on the old default as we now have active beta testers, but it's probably good to fix this sooner than later.

**Comment by judepereira** [comment]
@wilzbach since we're using appdirs now, is this issue still relevant?

**Comment by wilzbach** [comment]
No
