### ISSUE TITLE
Rebrand to Storyscript

### ISSUE THREAD

**Issue by judepereira** [storyscript/cli#139]
- [x] change all messaging s/asyncy/storyscript/g
- [x] update brew package
- [x] update circle pipeline
- [x] change all URL endpoints
- [x] update README (and image)

**Comment by kenneth-reitz** [comment]
Two of the checkmark items are all set, I believe. See the PR for progress. Still need to do brew package, PyPI and the README.

**Comment by wilzbach** [comment]
We also still need to update the Circle Pipeline for SLS and Storyscript, but I can quickly do that once @kenneth-reitz has created an account ;-)

**Comment by judepereira** [comment]
Done. Home-brew + pypi + packaging around the CLI.
