### ISSUE TITLE
Cache app_uuid on disk

### ISSUE THREAD

**Issue by judepereira** [storyscript/cli#156]
Instead of resolving it every time in https://github.com/storyscript/cli/blob/428d2164fe884f2a00c267f4fc9a8a9e9a36c16c/story/api.py#L190-L191, we can just cache it on disk, increasing the speed of the CLI completely.

**Comment by kenneth-reitz** [comment]
should we just store that instead of the app name in `story.yml` (or in addition to?)

**Comment by kenneth-reitz** [comment]
`appdirs` is very useful for this: https://github.com/ActiveState/appdirs

**Comment by judepereira** [comment]
No, let's not expose this in story.yml.

**Comment by wilzbach** [comment]
Heroku caches it in `.git/config` - though I always disliked this. However, it does make sense to store it in the directory of the story (e.g. `.story`) as then the information will be kept when the directory is moved to a different machine.

**Comment by kenneth-reitz** [comment]
we could just have a global cache of appnames -> ids per installation

**Comment by wilzbach** [comment]
> we could just have a global cache of appnames -> ids per installation

Then this information wouldn't be synced to other machines (think Dropbox, Backups, shared drives etc.)

**Comment by judepereira** [comment]
> Then this information wouldn't be synced to other machines (think Dropbox, Backups, shared drives etc.)

We don't have much to sync right now. At this time, I really dislike the fact that some services as simple as CircleCI need a directory for their single config.yaml file. Let's hold off introducing a `.story` directory in the project root until we really need it.

**Comment by judepereira** [comment]
For now - the app_uuid can be stored somewhere temporary, and not in the project root. This information will be auto cached on somebody else's system when they interact with the CLI.

**Comment by kenneth-reitz** [comment]
i got this

**Comment by judepereira** [comment]
@kenneth-reitz can you include the PR?

**Comment by kenneth-reitz** [comment]
https://github.com/storyscript/cli/pull/178
