### ISSUE TITLE
Use the project root dir when running the "test"/"deploy" command

### ISSUE THREAD

**Issue by judepereira** [storyscript/cli#169]
When I'm in a nested directory in my project, all the stories in the root of my project are not tested. This could also mean that they are not deployed.

My project structure:
```
$ tree ../../
../../
├── LICENSE
├── README.md
├── asyncy.yml
└── src
    ├── analytics
    │   └── router.story
    ├── cli
    │   ├── login.story
    │   └── logs.story
    ├── handlers
    │   ├── github_webhooks.story
    │   ├── jira_sync.story
    │   └── slack_whitelist_handler.story
    ├── health.story
    └── omg
        └── validate.story

5 directories, 11 files
```

`story test` only tests for stories in my current working directory, and not all the stories in my project:
```
$ story test
Compiling Stories…
 - github_webhooks.story ✔
 - jira_sync.story ✔
 - slack_whitelist_handler.story ✔

Looking good! 🎉

Deploy your app with:
  $ story deploy
h2:handlers jude$
```

**Comment by kenneth-reitz** [comment]
it works on deploy, but not on test?

**Comment by judepereira** [comment]
I don't think it works on deploy either.

**Comment by kenneth-reitz** [comment]
i'll take a look, but not sure how the deployment mechanism works. Do we want to find all the stories and then just treat them like they're in the root dir?

**Comment by judepereira** [comment]
Yes, all stories should be tested + compiled + deployed, as if the command was executed from the project root.

**Comment by kenneth-reitz** [comment]
will take a look
