### ISSUE TITLE
Show the magic!

### ISSUE THREAD

**Issue by stevepeak** [storyscript/cli#190]
# Show the magic of deployment! 

![d7c0acp-74dd66df-9f43-44aa-aabb-c9abc442af4c](https://user-images.githubusercontent.com/2041757/58870426-75d13b00-86c0-11e9-9c95-3b371b707088.png)

## Ideas
- Where is it deployed (what region/cloud provider).
- How was it deployed (Kubernetes)
- How many containers were orchestrated?
- How many functions where packaged?
- Subscribing ingress/pubsub?

This feeds into `story inspect` command and a command to expose the k8s configurations.

A couple customers have asked the questions above. It will be important to expose the key data and add a `-v/--verbose` flag to show much more magic.

:sparkles::cake::sparkles:

**Comment by kenneth-reitz** [comment]
Agreed, a `-v` on deploy would be very handy. We can do it for first-deploy automatically too.

**Comment by kenneth-reitz** [comment]
This will require some changes to the runtime, according to @judepereira.

Jude, can you start work on the required components?

**Comment by williammartin** [comment]
Roughly agreed upon:

```
Deploying story "dancing-gorilla-25" …

Compiled N stories ✔️

Discovered N services ✔️
Pulled and deployed N services ✔️
Configured service subscriptions ✔️
Configured ingress route (https://dancing-gorilla-25.storyscriptapp.com/) ✔️
Configured logging (story logs -f) ✔️ 
Configured health checks ✔️

Completed deploying story "dancing-gorilla-25" ✔️
```
