### ISSUE TITLE
Command: delete

### ISSUE THREAD

**Issue by wilzbach** [storyscript/cli#193]
There probably should be a way to delete an account and all its linked apps.

**Comment by kenneth-reitz** [comment]
I favor 'all it's linked app' to deleting the account itself. Let's work on that first. 

I have to do this sometimes, by hand, and it's really annoying.

`$ story apps delete --all --yes`

**Comment by kenneth-reitz** [comment]
Account deletion is another story.

**Comment by kenneth-reitz** [comment]
https://github.com/storyscript/cli/pull/200

**Comment by wilzbach** [comment]
> Account deletion is another story.

Yup, do we want to support this in the CLI?

**Comment by kenneth-reitz** [comment]
i'd say just on the dashboard.

**Comment by kenneth-reitz** [comment]
Oh, I have an idea.

`story account --delete`

`story account` returns your currently logged in username.

`story account login`

**Comment by wilzbach** [comment]
That's pretty nice!
