### ISSUE TITLE
story test in directory without story.yaml crashes ugly

### ISSUE THREAD

**Issue by acjay** [storyscript/cli#211]
In trying to experiment with my first `.story` file, I thought I'd run `story test` to see if I made any mistakes. Because I missed the `story app create` step, the `story test` crashed [here](https://github.com/storyscript/cli/blob/master/story/commands/test.py#L76). As far as I can see, the contents of this YAML file aren't at all when running this specific command. It's possible [a different caller](https://github.com/storyscript/cli/blob/e97cec40658cf628055828557bbe69cba4d4b620/story/commands/deploy.py#L23-L32) needs this info, but if so, it's not obvious on the surface where it's needed, or that the YAML couldn't be loaded outside of `compile_app`.

The result is a not particularly informative crash with a stack trace.

**Comment by judepereira** [comment]
Thanks @acjay! I've made it mandatory to have Asyncy.yml now, since it will be required by `test` in the near future.
