### ISSUE TITLE
unable to login via `story login`

### ISSUE THREAD

**Issue by climateamante** [storyscript/cli#214]
**`Error when attempting to login via the CLI`**

**Steps to reproduce the issue:**
1. `story login`

**Describe the results you received:**

1. ``https://stories.storyscriptapp.com/github?state=266f8f02-2479-4718-94a5-9505afc5af24``

1. when going to the URL - error response:
``HTTP 500: Story execution failed``

**Describe the results you expected:**
Being able to login

**Output of `storyscript version`:**

```sh
Storyscript CLI: v0.15.1, Storyscript Compiler: v0.20.1.
```

**Comment by wilzbach** [comment]
Hi @climateamante. Thanks a lot for your interest and idea. As this issue is about the CLI, I transferred it to the respective repository.

**Comment by judepereira** [comment]
@climateamante thanks for letting us know. There was a database issue during that time. It's now available and works well :)

Let us know if you face any other issues!
