### ISSUE TITLE
Docs link in description returns 404 error

### ISSUE THREAD

**Issue by ibrahim0814** [storyscript/cli#222]
Nothing too major but the link in y'alls description of this repository returns a 404 error when clicked

![Screen Shot 2019-06-27 at 1 08 16 PM](https://user-images.githubusercontent.com/24867409/60297273-adf12580-98dc-11e9-93d7-ab27af588b25.jpg)

**Comment by judepereira** [comment]
Changed to https://docs.storyscript.io/quick-start/

Thank you @ibrahim0814 for reporting this in :)
