### ISSUE TITLE
HTTP 500: Story execution failed

### ISSUE THREAD

**Issue by darkLord19** [storyscript/cli#234]
story login and story create apps command are producing HTTP 500: Story execution failed.

**Comment by wilzbach** [comment]
Hi there. As your issue is with the Story CLI I transferred it to the respective repository. Do you by any chance have more logs or information on what story you were trying to run?

**Comment by darkLord19** [comment]
Nothing specific. I was trying to create new story by running story create apps then it opened a webpage for GitHub oauth which I approved and then I got the above error.

**Comment by darkLord19** [comment]
I wasn't part of the cloud beta before. Could that be the cause of the issue? After Jude added me to cloud beta I am not facing the error.
